### PR TITLE
Update cluecumber version to 2.6.1

### PR DESCRIPTION
**Pull request by codingHahn**

### CODE REVIEW

**Comment by JavaanseHZ** [comment]
Will have a look later tonight why it failed.

**Comment by codingHahn** [comment]
Thanks. Seems to be the release-publish step. It built just fine locally

**Comment by JavaanseHZ** [comment]
ah, oki, it even says so in the logs :) it's a security restriction of travis for PRs from forks:
https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
I'll see if I can fix it - it shouldn't even go to that step if it's a PR...

**Comment by JavaanseHZ** [comment]
oki - i'll think i have to dig into travis stage conditions again, but this should work for now.

**Comment by codingHahn** [comment]
Thanks for responding this quickly. By the way, Travis is discontinuing their free open source tier: https://news.ycombinator.com/item?id=25338983

**Comment by JavaanseHZ** [comment]
No worries 🙂 I looked at the cluecumber changes and saw no structural stuff, but let me know if something is missing. And that's a shame with travis - will have to see what happens when the minutes run out and what alternatives there are.

**Pull request merged**
